# Generated by Django 6.0.2 on 2026-02-27 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "connection_type",
                    models.CharField(
                        choices=[("discord", "Discord")],
                        default="discord",
                        max_length=32,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionDiscord",
            fields=[
                (
                    "connection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="connections.connection",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        help_text="Discord Incoming Webhook URL for this channel/server."
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True,
                        help_text="Optional Bot token (needed for message editing).",
                        max_length=255,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Channel ID (required when using bot token to edit messages).",
                        max_length=64,
                    ),
                ),
                (
                    "can_edit_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether previously sent messages can be edited via this connection.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Connection",
                "verbose_name_plural": "Discord Connections",
            },
            bases=("connections.connection",),
        ),
    ]
