# Generated by Django 6.0.2 on 2026-02-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectiondiscord",
            name="bot_token",
        ),
        migrations.RemoveField(
            model_name="connectiondiscord",
            name="channel_id",
        ),
        migrations.AlterField(
            model_name="connectiondiscord",
            name="can_edit_sent",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, editing a sent message will update it in Discord. Requires the original Discord message ID to have been stored on send.",
            ),
        ),
    ]
