# Generated by Django 6.0.2 on 2026-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="headline_enable",
            field=models.BooleanField(
                default=False,
                help_text="Show the Headline field in the message editor.",
            ),
        ),
    ]
