# Generated by Django 4.2.28 on 2026-04-06 17:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userpreferences_history_expand_all"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.BNUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="ui_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Namespaced UI preference blob (keyed by feature slug).",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="userpreferences",
            name="sidebar_width",
            field=models.PositiveIntegerField(
                default=280, help_text="History sidebar width in pixels (180-750)."
            ),
        ),
    ]
