# Generated by Django 6.0.2 on 2026-02-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="last_error",
            field=models.TextField(
                blank=True,
                help_text="Error detail from the most recent failed send attempt.",
            ),
        ),
    ]
