# Generated by Django 6.0.2 on 2026-02-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_add_last_error_to_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="headline",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
