# Generated by Django 6.0.2 on 2026-03-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_partial_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Accepted: images (PNG, JPG, GIF, WEBP) and PDF files.",
                null=True,
                upload_to="message_images/",
            ),
        ),
    ]
